name: Test and report coverage
description: Test and report coverage
inputs:
  suffix:
    description: Suffix to include when formatting result names.
    default: ""
  token:
    description: Codecov token for the repository.
    required: true
    default: ""

runs:
  using: composite
  steps:
    - name: Run unit tests
      run: ci/run_tests.sh
      shell: bash -el {0}

    - name: Upload test results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: ${{ inputs.suffix != '' && format('test-results-{0}', inputs.suffix) || 'test-results' }}
        path: test-data.xml
        overwrite: true

    - name: Collect coverage
      run: coverage report -m
      shell: bash -el {0}

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
      with:
        token: ${{ inputs.token }}
        files: ./coverage.xml
        flags: unittests
        name: grammatica
        fail_ci_if_error: false
        disable_telem: true

    - name: Run docstring tests
      run: python3 scripts/test_docstrings.py --raise-on-error
      shell: bash -el {0}
